export const SCRAPE_PROGRESS_TYPES = {
  START_SCRAPING: 'START_SCRAPING',
  LOGGING_IN: 'LOGGING_IN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  END_SCRAPING: 'END_SCRAPING',
};

export const LOGIN_RESULT = {
  SUCCESS: 'SUCCESS',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
};

export const NAVIGATION_ERRORS = {
  TIMEOUT: 'TIMEOUT',
  GENERIC: 'GENERIC',
};

export const GENERAL_ERROR = 'GENERAL_ERROR';
